version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "America/Edmonton"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 3
    groups:
      github-actions-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "America/Edmonton"
    labels:
      - "dependencies"
      - "dotnet"
    open-pull-requests-limit: 5
    groups:
      nuget-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/src/NovaPointConsoleTester"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "America/Edmonton"
    labels:
      - "dependencies"
      - "dotnet"
    open-pull-requests-limit: 5
    groups:
      nuget-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/src/NovaPointLibrary"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "America/Edmonton"
    labels:
      - "dependencies"
      - "dotnet"
    open-pull-requests-limit: 5
    groups:
      nuget-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/src/NovaPointWPF"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "America/Edmonton"
    labels:
      - "dependencies"
      - "dotnet"
    open-pull-requests-limit: 5
    groups:
      nuget-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

